server:
  port: 8003
spring:
  application:
    name: gateway
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: lb://inventory
          filters:
            - CircuitBreaker=name=default,fallbackUri=forward:/fallback/inventory
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
