server:
  port: 8003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # Filtros que se aplican a TODAS las rutas
      default-filters:
        - AddResponseHeader=X-Gateway, Spring-Cloud-Gateway
      
      routes:
        # Servicio de Inventory
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: inventoryCircuitBreaker
                fallbackUri: forward:/fallback/inventory
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
      
      # CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
