server:
    port: 8003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: inventory_route
          uri: lb://INVENTORY
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<remaining>.*), /${remaining}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
