server:
    port: 8003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: inventory_route
          uri: lb://inventory
          predicates:
            - Path=/api/v1/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
