spring:
  application:
    name: gateway
server:
  port: 8003
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
cloud:
  gateway:
    routes:
        - id: example-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/example/**
          filters:
            - CircuitBreaker=name=default
