server:
  port: 8003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, Spring-Cloud-Gateway
      routes:
        - id: fallback_route
          uri: forward:/fallback
          predicates:
            - Path=/fallback/**
          filters:
            - StripPrefix=1
        # Servicio de Inventory
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: inventoryCircuitBreaker
                fallbackUri: forward:/fallback/inventory
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
      # CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
