spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: inventory
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL} 
    username: ${SPRING_DATASOURCE_USERNAME} 
    password: ${SPRING_DATASOURCE_PASSWORD} 
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
server:
  port: 8001
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
logging:
  level:
    # 1. ¡ESTE ES EL CRUCIAL! Muestra todo el flujo interno de rutas y filtros.
    org.springframework.cloud.gateway: TRACE 
    
    # 2. Útil para ver cómo el Load Balancer resuelve 'lb://inventory' a la IP:Puerto.
    org.springframework.cloud.loadbalancer: DEBUG 
    
    # 3. Muestra detalles de la red subyacente (qué intenta conectar).
    reactor.netty: DEBUG
        failure-rate-threshold: 50
