spring:
  application:
    name: products
  cloud:
    function:
      definition: createProduct;updateProduct;deleteProduct;createCategory;updateCategory;deleteCategory
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
      bindings:
        createCategory-in-0:
          destination: category.created
          group: products-group
          content-type: application/json
        updateCategory-in-0:
          destination: category.updated
          group: products-group
          content-type: application/json
        deleteCategory-in-0:
          destination: category.deleted
          group: products-group
          content-type: application/json
        createProduct-in-0:
          destination: product.created
          group: products-group
          content-type: application/json
        updateProduct-in-0:
          destination: product.updated
          group: products-group
          content-type: application/json
        deleteProduct-in-0:
          destination: product.deleted
          group: products-group
          content-type: application/json
  data:
    mongodb:
      uri: ${MONGODB_HOST}
meilisearch:
  api-key: ${MEILISEARCH_API_KEY} 
  host-url: ${MEILISEARCH_HOST}
server:
  port: 8002
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
