spring:
  application:
    name: products
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
      bindings:
        productConsumer-in-0:
          destination: inventory
          group: products-group
          content-type: application/json
  data:
    mongodb:
      uri: ${MONGODB_HOST}
meilisearch:
  api-key: ${MEILISEARCH_API_KEY} 
  host-url: ${MEILISEARCH_HOST}
server:
  port: 8002
resilience4j:
  circuitbreaker:
    instances:
      products:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
