spring:
  application:
    name: products
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
      bindings:
        createProduct-in-0:
          destination: product.created
          group: products-group
          content-type: application/json
        updateProduct-in-0:
          destination: product.updated
          group: products-group
          content-type: application/json
        deleteProduct-in-0:
          destination: product.deleted
          group: products-group
          content-type: application/json
  data:
    mongodb:
      uri: ${MONGODB_HOST}
meilisearch:
  api-key: ${MEILISEARCH_API_KEY} 
  host-url: ${MEILISEARCH_HOST}
server:
  port: 8002
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
