spring:
  application:
    name: products
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
      bindings:
        productConsumer-in-0:
          destination: inventory
          group: products-group
          content-type: application/json
  data:
    mongodb:
      uri: ${MONGODB_HOST}
meilisearch:
  api-key: ${MEILISEARCH_API_KEY} 
  host-url: ${MEILISEARCH_HOST}
server:
  port: 8002
